version: '3'
services:

  mongodb:
    image: mongo
    container_name: demo_mongo
    #ports:
      #- "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

  server:
    container_name: demo_server
    depends_on:
      - mongodb
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOSTNAME: demo_server
      SERVER_URL: http://demo_server:${SERVER_PORT}

      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOSTNAME: demo_mongo
      MONGO_COLLECTION: ${MONGO_COLLECTION}

      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}

      API_GEOGRAPHIE: ${API_GEOGRAPHIE}
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network

  client:
    container_name: demo_client
    depends_on:
      - server
    environment:
      VUE_APP_PORT: ${VUE_APP_PORT}
      VUE_APP_HOSTNAME: demo_client
      SERVER_URL: http://localhost:${SERVER_PORT} #browser hostname
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network

  sensors:
    container_name: demo_sensors
    environment:
      SERVER_URL: http://demo_server:${SERVER_PORT}
    build:
      context: ./sensors
      dockerfile: Dockerfile
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongodb_data: