version: '3'
services:

  mongodb:
    image: mongo
    container_name: demo_mongo
    #ports:
      #- "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

  server:
    container_name: demo_server
    depends_on:
      - mongodb
    environment:
      SERVER_PORT: 3000
      SERVER_HOSTNAME: demo_server
      SERVER_URL: http://demo_server:3000
      MONGO_URI: "mongodb://mongodb:27017/demo_epitech"
      API_GEOGRAPHIE: https://geo.api.gouv.fr
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network

  client:
    container_name: demo_client
    depends_on:
      - server
    environment:
      VUE_APP_PORT: 8080
      VUE_APP_HOSTNAME: demo_client
      SERVER_URL: http://localhost:3000 #browser hostname
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network

  sensors:
    container_name: demo_sensors
    environment:
      SERVER_URL: http://demo_server:3000
    build:
      context: ./sensors
      dockerfile: Dockerfile
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongodb_data: